project 'SwiftPad.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftPad' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftPad
  pod 'Alamofire', '~> 4.0.1'
  pod 'SnapKit', '~> 3.0.2'
  pod 'YYKit', '~> 1.0.9'
  pod 'SDWebImage', '~> 4.0.0-beta2'
  pod 'Refresher', '~> 0.6.1'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'BetterSegmentedControl', '~> 0.5'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'AlamofireImage', '~> 3.1.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'UMengSocial', '~> 5.0'
  
  target 'SwiftPadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftPadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
